### ISSUE TITLE
Image comparison test failed

### ISSUE THREAD

**Issue by EnbangWu** [etro-js/etro#132] opened 2022-07-17 17:51 UTC
Firefox 102.0 (Mac OS 10.15) Effects Grayscale should desaturate the target FAILED
	Expected 93.75 to be less than or equal 1.
	<Jasmine>
	compareImageData/</<@spec/effect.spec.js:82:28
	triggerDataUpdate@node_modules/resemblejs/resemble.js:224:43
	onceWeHaveBoth@node_modules/resemblejs/resemble.js:825:21
	onLoadImage@node_modules/resemblejs/resemble.js:304:21
	resemble/loadImageData/hiddenImage.onload@node_modules/resemblejs/resemble.js:330:28
Firefox 102.0 (Mac OS 10.15) Effects Contrast should change the contrast FAILED
	Expected $['0'] = 0 to equal 255.
	<Jasmine>
	@spec/effect.spec.js:294:32
	<Jasmine>
...........
Firefox 102.0 (Mac OS 10.15) Effects Channels should multiply each channel by a constant FAILED
	Expected $['0'] = 0 to equal 255.
	<Jasmine>
	@spec/effect.spec.js:321:32
	<Jasmine>
Firefox 102.0 (Mac OS 10.15) Effects Brightness should change the brightness FAILED
	Expected $['0'] = 0 to equal 255.
	Expected $['1'] = 0 to equal 5.
	Expected $['2'] = 0 to equal 5.
	<Jasmine>
	@spec/effect.spec.js:279:32
	<Jasmine>
.
Firefox 102.0 (Mac OS 10.15) Effects ChromaKey should make the target color transparent FAILED
	Expected 255 to be 0.
	<Jasmine>
	@spec/effect.spec.js:348:23
	<Jasmine>
..
Firefox 102.0 (Mac OS 10.15) Effects GaussianBlurVertical should blur with 5-pixel radius FAILED
	Expected 99.22 to be less than or equal 1.
	<Jasmine>
	compareImageData/</<@spec/effect.spec.js:82:28
	triggerDataUpdate@node_modules/resemblejs/resemble.js:224:43
	onceWeHaveBoth@node_modules/resemblejs/resemble.js:825:21
	onLoadImage@node_modules/resemblejs/resemble.js:304:21
	resemble/loadImageData/hiddenImage.onload@node_modules/resemblejs/resemble.js:330:28
Firefox 102.0 (Mac OS 10.15) Effects GaussianBlurHorizontal should blur with 5-pixel radius FAILED
	Expected 98.83 to be less than or equal 1.
	<Jasmine>
	compareImageData/</<@spec/effect.spec.js:82:28
	triggerDataUpdate@node_modules/resemblejs/resemble.js:224:43
	onceWeHaveBoth@node_modules/resemblejs/resemble.js:825:21
	onLoadImage@node_modules/resemblejs/resemble.js:304:21
	resemble/loadImageData/hiddenImage.onload@node_modules/resemblejs/resemble.js:330:28
.....
Firefox 102.0 (Mac OS 10.15) Effects Pixelate should decimate to 3-pixel texels FAILED
	Expected 100 to be less than or equal 1.
	<Jasmine>
	compareImageData/</<@spec/effect.spec.js:82:28
	triggerDataUpdate@node_modules/resemblejs/resemble.js:224:43
	onceWeHaveBoth@node_modules/resemblejs/resemble.js:825:21
	onLoadImage@node_modules/resemblejs/resemble.js:304:21
	resemble/loadImageData/hiddenImage.onload@node_modules/resemblejs/resemble.js:330:28
.....................................................................
Firefox 102.0 (Mac OS 10.15): Executed 140 of 140 (8 FAILED) (20.11 secs / 20 secs)

**Comment by clabe45** [comment] 2023-11-12 00:26
This is an issue with the effects, not the tests. The expected and actual images shouldn't be that different.

**Comment by clabe45** [comment] 2024-01-16 00:43
Duplicate of #250 (more details there)

**Closed by clabe45** 2024-01-16 00:43 UTC
Labels: type:bug, help wanted, priority:high
